// <auto-generated />
using System;
using F1VacationSite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace F1VacationSite.Migrations
{
    [DbContext(typeof(VacationDbContext))]
    [Migration("20260420200746_FixReviews")]
    partial class FixReviews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("F1VacationSite.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("F1VacationSite.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Melbourne",
                            Name = "Crown Towers Melbourne",
                            Stars = 5
                        },
                        new
                        {
                            Id = 2,
                            City = "Shanghai",
                            Name = "The Ritz-Carlton Shanghai",
                            Stars = 5
                        },
                        new
                        {
                            Id = 3,
                            City = "Suzuka",
                            Name = "Suzuka Circuit Hotel",
                            Stars = 4
                        },
                        new
                        {
                            Id = 4,
                            City = "Miami",
                            Name = "1 Hotel South Beach",
                            Stars = 5
                        },
                        new
                        {
                            Id = 5,
                            City = "Montreal",
                            Name = "Fairmont The Queen Elizabeth",
                            Stars = 4
                        },
                        new
                        {
                            Id = 6,
                            City = "Monte Carlo",
                            Name = "Hotel de Paris Monte-Carlo",
                            Stars = 5
                        },
                        new
                        {
                            Id = 7,
                            City = "Barcelona",
                            Name = "Hotel Arts Barcelona",
                            Stars = 5
                        },
                        new
                        {
                            Id = 8,
                            City = "Spielberg",
                            Name = "Falkensteiner Hotel Schladming",
                            Stars = 4
                        },
                        new
                        {
                            Id = 9,
                            City = "Towcester",
                            Name = "Whittlebury Hall Hotel",
                            Stars = 4
                        },
                        new
                        {
                            Id = 10,
                            City = "Spa",
                            Name = "Radisson Blu Palace Hotel Spa",
                            Stars = 4
                        },
                        new
                        {
                            Id = 11,
                            City = "Budapest",
                            Name = "Kempinski Hotel Corvinus",
                            Stars = 5
                        },
                        new
                        {
                            Id = 12,
                            City = "Zandvoort",
                            Name = "NH Zandvoort",
                            Stars = 4
                        },
                        new
                        {
                            Id = 13,
                            City = "Monza",
                            Name = "Hotel de la Ville Monza",
                            Stars = 5
                        },
                        new
                        {
                            Id = 14,
                            City = "Madrid",
                            Name = "Gran Melia Palacio de los Duques",
                            Stars = 5
                        },
                        new
                        {
                            Id = 15,
                            City = "Baku",
                            Name = "Four Seasons Hotel Baku",
                            Stars = 5
                        },
                        new
                        {
                            Id = 16,
                            City = "Singapore",
                            Name = "Marina Bay Sands",
                            Stars = 5
                        },
                        new
                        {
                            Id = 17,
                            City = "Austin",
                            Name = "JW Marriott Austin",
                            Stars = 4
                        },
                        new
                        {
                            Id = 18,
                            City = "Mexico City",
                            Name = "Four Seasons Mexico City",
                            Stars = 5
                        },
                        new
                        {
                            Id = 19,
                            City = "Sao Paulo",
                            Name = "Hotel Unique Sao Paulo",
                            Stars = 5
                        },
                        new
                        {
                            Id = 20,
                            City = "Las Vegas",
                            Name = "The Venetian Las Vegas",
                            Stars = 5
                        },
                        new
                        {
                            Id = 21,
                            City = "Doha",
                            Name = "The Ned Doha",
                            Stars = 5
                        },
                        new
                        {
                            Id = 22,
                            City = "Abu Dhabi",
                            Name = "Emirates Palace Abu Dhabi",
                            Stars = 5
                        });
                });

            modelBuilder.Entity("F1VacationSite.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Circuit")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Circuit = "Bahrain International Circuit",
                            Country = "Bahrain",
                            EndDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bahrain Grand Prix",
                            StartDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Circuit = "Jeddah Corniche Circuit",
                            Country = "Saudi Arabia",
                            EndDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Saudi Arabian Grand Prix",
                            StartDate = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Circuit = "Albert Park",
                            Country = "Australia",
                            EndDate = new DateTime(2026, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Australian Grand Prix",
                            StartDate = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Circuit = "Baku City Circuit",
                            Country = "Azerbaijan",
                            EndDate = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Azerbaijan Grand Prix",
                            StartDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Circuit = "Miami International Autodrome",
                            Country = "United States",
                            EndDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Miami Grand Prix",
                            StartDate = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Circuit = "Imola",
                            Country = "Italy",
                            EndDate = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Emilia Romagna Grand Prix",
                            StartDate = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Circuit = "Monte Carlo",
                            Country = "Monaco",
                            EndDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Monaco Grand Prix",
                            StartDate = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Circuit = "Circuit de Barcelona-Catalunya",
                            Country = "Spain",
                            EndDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Spanish Grand Prix",
                            StartDate = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Circuit = "Circuit Gilles Villeneuve",
                            Country = "Canada",
                            EndDate = new DateTime(2026, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Canadian Grand Prix",
                            StartDate = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Circuit = "Red Bull Ring",
                            Country = "Austria",
                            EndDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Austrian Grand Prix",
                            StartDate = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Circuit = "Silverstone",
                            Country = "United Kingdom",
                            EndDate = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "British Grand Prix",
                            StartDate = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Circuit = "Hungaroring",
                            Country = "Hungary",
                            EndDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hungarian Grand Prix",
                            StartDate = new DateTime(2026, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Circuit = "Spa-Francorchamps",
                            Country = "Belgium",
                            EndDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Belgian Grand Prix",
                            StartDate = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Circuit = "Zandvoort",
                            Country = "Netherlands",
                            EndDate = new DateTime(2026, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dutch Grand Prix",
                            StartDate = new DateTime(2026, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Circuit = "Monza",
                            Country = "Italy",
                            EndDate = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Italian Grand Prix",
                            StartDate = new DateTime(2026, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Circuit = "Marina Bay Street Circuit",
                            Country = "Singapore",
                            EndDate = new DateTime(2026, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Singapore Grand Prix",
                            StartDate = new DateTime(2026, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Circuit = "Suzuka",
                            Country = "Japan",
                            EndDate = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Japanese Grand Prix",
                            StartDate = new DateTime(2026, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Circuit = "Circuit of The Americas",
                            Country = "United States",
                            EndDate = new DateTime(2026, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "United States Grand Prix",
                            StartDate = new DateTime(2026, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            Circuit = "Autódromo Hermanos Rodríguez",
                            Country = "Mexico",
                            EndDate = new DateTime(2026, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mexico City Grand Prix",
                            StartDate = new DateTime(2026, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            Circuit = "Interlagos",
                            Country = "Brazil",
                            EndDate = new DateTime(2026, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Brazilian Grand Prix",
                            StartDate = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            Circuit = "Las Vegas Street Circuit",
                            Country = "United States",
                            EndDate = new DateTime(2026, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Las Vegas Grand Prix",
                            StartDate = new DateTime(2026, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            Circuit = "Yas Marina Circuit",
                            Country = "United Arab Emirates",
                            EndDate = new DateTime(2026, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Abu Dhabi Grand Prix",
                            StartDate = new DateTime(2026, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("F1VacationSite.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialRequest")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("F1VacationSite.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("F1VacationSite.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nights")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("RaceId");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Пакетът включва престой в сърцето на Мелбърн с директен изглед към Albert Park. Идеален за феновете, търсещи комфорт и близост до пистата.",
                            HotelId = 1,
                            Nights = 5,
                            Price = 3200m,
                            RaceId = 3
                        },
                        new
                        {
                            Id = 2,
                            Description = "Петзвездно изживяване в легендарното Monte Carlo. Хотелът се намира на метри от пистата — усети магията на Monaco GP от първа ръка.",
                            HotelId = 6,
                            Nights = 5,
                            Price = 4800m,
                            RaceId = 7
                        },
                        new
                        {
                            Id = 3,
                            Description = "Miami GP с престой в един от най-стилните хотели на South Beach. Съчетай Формула 1 с плажния живот на Маями.",
                            HotelId = 4,
                            Nights = 4,
                            Price = 3500m,
                            RaceId = 5
                        },
                        new
                        {
                            Id = 4,
                            Description = "Singapore GP е единственото нощно състезание в календара. Marina Bay Sands предлага невероятна гледка към градските светлини и пистата.",
                            HotelId = 16,
                            Nights = 4,
                            Price = 3800m,
                            RaceId = 16
                        },
                        new
                        {
                            Id = 5,
                            Description = "British GP в Silverstone е едно от най-емблематичните събития в спорта. Whittlebury Hall е само минути от пистата сред английската провинция.",
                            HotelId = 9,
                            Nights = 5,
                            Price = 2700m,
                            RaceId = 11
                        },
                        new
                        {
                            Id = 6,
                            Description = "Italian GP в Monza — домът на тифозите. Почувствай страстта на италианските фенове сред историческия парк.",
                            HotelId = 13,
                            Nights = 4,
                            Price = 2500m,
                            RaceId = 15
                        },
                        new
                        {
                            Id = 7,
                            Description = "Las Vegas GP е най-екстравагантното събитие в календара. The Venetian предлага луксозно изживяване в центъра на Strip-а.",
                            HotelId = 20,
                            Nights = 4,
                            Price = 4200m,
                            RaceId = 21
                        },
                        new
                        {
                            Id = 8,
                            Description = "Azerbaijan GP на улиците на Баку е едно от най-непредсказуемите състезания. Four Seasons е само на крачка от пистата.",
                            HotelId = 15,
                            Nights = 4,
                            Price = 2900m,
                            RaceId = 4
                        },
                        new
                        {
                            Id = 9,
                            Description = "Hungarian GP в Будапеща съчетава страхотно състезание с богата култура. Kempinski е в самия център на столицата.",
                            HotelId = 11,
                            Nights = 4,
                            Price = 2300m,
                            RaceId = 12
                        },
                        new
                        {
                            Id = 10,
                            Description = "Финалното състезание на сезона в Abu Dhabi е незабравимо. Emirates Palace е един от най-луксозните хотели в света.",
                            HotelId = 22,
                            Nights = 5,
                            Price = 3600m,
                            RaceId = 22
                        },
                        new
                        {
                            Id = 11,
                            Description = "Spanish GP в Барселона е класика от Формула 1 календара. Hotel Arts предлага панорамна гледка към Средиземно море.",
                            HotelId = 7,
                            Nights = 4,
                            Price = 2100m,
                            RaceId = 8
                        },
                        new
                        {
                            Id = 12,
                            Description = "Japanese GP в Suzuka е любимото на истинските фенове. Suzuka Circuit Hotel е буквално в рамките на пистата.",
                            HotelId = 3,
                            Nights = 5,
                            Price = 2800m,
                            RaceId = 17
                        },
                        new
                        {
                            Id = 13,
                            Description = "Belgian GP в Spa-Francorchamps е едно от най-красивите и предизвикателни трасета в света. Radisson Blu е в сърцето на Spa.",
                            HotelId = 10,
                            Nights = 4,
                            Price = 2000m,
                            RaceId = 13
                        },
                        new
                        {
                            Id = 14,
                            Description = "Canadian GP в Монреал съчетава вълнуващо състезание с космополитния чар на града. Fairmont Queen Elizabeth е иконата на Монреал.",
                            HotelId = 5,
                            Nights = 5,
                            Price = 2600m,
                            RaceId = 9
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("F1VacationSite.Models.Reservation", b =>
                {
                    b.HasOne("F1VacationSite.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1VacationSite.Data.Models.ApplicationUser", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("F1VacationSite.Models.Review", b =>
                {
                    b.HasOne("F1VacationSite.Models.Trip", "Trip")
                        .WithMany("Reviews")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1VacationSite.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("F1VacationSite.Models.Trip", b =>
                {
                    b.HasOne("F1VacationSite.Models.Hotel", "Hotel")
                        .WithMany("Trips")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1VacationSite.Models.Race", "Race")
                        .WithMany("Trips")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("F1VacationSite.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("F1VacationSite.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1VacationSite.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("F1VacationSite.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("F1VacationSite.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("F1VacationSite.Models.Hotel", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("F1VacationSite.Models.Race", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("F1VacationSite.Models.Trip", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
