// <auto-generated />
using System;
using F1VacationSite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace F1VacationSite.Migrations
{
    [DbContext(typeof(VacationDbContext))]
    [Migration("20260212181018_SeededData")]
    partial class SeededData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("F1VacationSite.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Melbourne",
                            Name = "Albert Park Hotel",
                            Stars = 4
                        },
                        new
                        {
                            Id = 2,
                            City = "Monte Carlo",
                            Name = "Monte Carlo Palace",
                            Stars = 5
                        },
                        new
                        {
                            Id = 3,
                            City = "Towcester",
                            Name = "Silverstone Inn",
                            Stars = 3
                        },
                        new
                        {
                            Id = 4,
                            City = "Monza",
                            Name = "Hotel Monza",
                            Stars = 4
                        },
                        new
                        {
                            Id = 5,
                            City = "Stavelot",
                            Name = "Spa Resort",
                            Stars = 4
                        },
                        new
                        {
                            Id = 6,
                            City = "Austin",
                            Name = "Austin Grand Hotel",
                            Stars = 4
                        },
                        new
                        {
                            Id = 7,
                            City = "Suzuka",
                            Name = "Suzuka Hotel & Suites",
                            Stars = 4
                        },
                        new
                        {
                            Id = 8,
                            City = "Montreal",
                            Name = "Gilles Village Hotel",
                            Stars = 3
                        });
                });

            modelBuilder.Entity("F1VacationSite.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Circuit")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Circuit = "Albert Park",
                            Country = "Australia",
                            EndDate = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Australian Grand Prix",
                            StartDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Circuit = "Monte Carlo",
                            Country = "Monaco",
                            EndDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Monaco Grand Prix",
                            StartDate = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Circuit = "Silverstone",
                            Country = "United Kingdom",
                            EndDate = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "British Grand Prix",
                            StartDate = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Circuit = "Monza",
                            Country = "Italy",
                            EndDate = new DateTime(2026, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Italian Grand Prix",
                            StartDate = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Circuit = "Spa-Francorchamps",
                            Country = "Belgium",
                            EndDate = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Belgian Grand Prix",
                            StartDate = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Circuit = "Circuit of The Americas",
                            Country = "United States",
                            EndDate = new DateTime(2026, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "United States Grand Prix",
                            StartDate = new DateTime(2026, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Circuit = "Suzuka",
                            Country = "Japan",
                            EndDate = new DateTime(2026, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Japanese Grand Prix",
                            StartDate = new DateTime(2026, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Circuit = "Circuit Gilles Villeneuve",
                            Country = "Canada",
                            EndDate = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Canadian Grand Prix",
                            StartDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("F1VacationSite.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("Nights")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("RaceId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("F1VacationSite.Models.Trip", b =>
                {
                    b.HasOne("F1VacationSite.Models.Hotel", "Hotel")
                        .WithMany("Trips")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1VacationSite.Models.Race", "Race")
                        .WithMany("Trips")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("F1VacationSite.Models.Hotel", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("F1VacationSite.Models.Race", b =>
                {
                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
